apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: my-rabbitmq-cluster
spec:
  replicas: 2
  resources:
    requests:
      memory: 16Gi
      cpu: '4'
    limits:
      memory: 16Gi
      cpu: '4'
  override:
    statefulSet:
      spec:
        template:
          spec:
            nodeSelector:
              restrict-scale-down: "true"
            containers:
            - name: rabbitmq
              image: docker.io/library/rabbitmq:3.10.7-management
              volumeMounts:
              - mountPath: /etc/rabbitmq/definitions.json
                subPath: definitions.json
                name: definitions
            volumes:
            - name: definitions
              configMap:
                name: definitions
  rabbitmq:
    envConfig: |
      RABBITMQ_DISTRIBUTION_BUFFER_SIZE=100000
    additionalConfig: |
      vm_memory_high_watermark.absolute = 32025908428
      loopback_users.guest = false
      disk_free_limit.absolute = 4GB
      load_definitions = /etc/rabbitmq/definitions.json
